<%-- 
    Document   : report30days
    Created on : May 30, 2019, 9:15:14 PM
    Author     : victor
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
       
          <%@page import="javax.swing.border.TitledBorder"%>
        <%@page import="java.sql.Connection"%>
        <%@page import="java.sql.ResultSet"%>
        <%@page import="java.sql.PreparedStatement"%>
        <%@page import="com.lowagie.text.DocumentException"%>
        <%@page import="com.lowagie.text.Paragraph"%>
        <%@page import="com.lowagie.text.html.HtmlWriter"%>
        <%@page import="com.lowagie.text.pdf.PdfWriter"%>
        <%@page import="com.lowagie.text.Document"%>
        <%@page import="java.io.*"%>;
        <%@page import="java.awt.*"%>
        <%@page import="javax.servlet.*"%>
        <%@page import="javax.servlet.http.*"%>
        <%@page import="com.lowagie.text.*"%>
        <%@page import="com.lowagie.text.pdf.*"%>
        <%@page import="com.lowagie.text.html.*"%>
      
        <%@page import="java.awt.*"%>
        <%@page import="java.io.IOException"%>
        <%@page import="javax.servlet.*"%>
        <%@page import="javax.servlet.http.*"%>
        <%@page import="com.lowagie.text.*"%>
        <%@page import="com.lowagie.text.pdf.*"%>
        <%@page import="com.lowagie.text.html.*"%>
        
        <%
            String str = "pdf";
            Document document = new Document();
            //  Document document = new Document();
                if (str.equals("pdf")) {
                    response.setContentType("application/pdf");
                    PdfWriter.getInstance(document, response.getOutputStream());
                }

                 document.open();

                /* new paragraph instance initialized and add function write in pdf file*/
                document.add(new Paragraph("---------------------------------------------------------CBBank SYSTEM REPORT"
                        + "---------------------------------------------------------\n\n"));
                document.add(new Paragraph("                              REPORT GENERATED BY: Victor Gachau Kingori \n\n"));
                document.add(new Paragraph("-----------------------------------------------------------------"
                        + "----------------------------------------------------------------"));
                document.addCreationDate();
                document.close();
            %>
    </body>
</html>
